# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 92419bed7a982896627ad6859111e3eaf0ed26ed9e7fedd690abe3cd2b57ac566979868274475257e30bb4198634648481d309ea7abfbfeca8c3c6cb19e6ee75

test:
  secret_key_base: 558a0571256657f60cf94ac6b5ed1500cb9761306c1ec599b3702e49613a34996b2bcb73db952ed62b7d87e9ee1a870a2c8e5d4d8453502610ef82aa63252f7f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
